@PersonApi_HostAddress = https://localhost:7123

GET {{PersonApi_HostAddress}}/person
Accept: application/json

###


POST {{PersonApi_HostAddress}}/weather
Content-Type: application/json
Accept: application/json

{
  "city": "Sofia",
  "days": 5
}